[workspace]
members = ["./tutorial1_window", "experimental", "tutorial2_surface", "tutorial3_pipeline"]
resolver = "2"

[workspace.dependencies]
winit = { version = "0.29.0", features = ["rwh_05"] }
env_logger = { version = "0.10" }
log = { version = "0.4" }
wgpu = { version = "24.0" }
cfg-if = { version = "1.0" }
pollster = "0.3"
